name: Deploy Frontend to EC2

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: innovatech-frontend
  IMAGE_TAG: latest

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./front_despacho

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 400 ~/.ssh/ec2_key.pem

      - name: Deploy on EC2 Frontend
        run: |
          ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONT_HOST }} << 'EOF'
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 699480004844.dkr.ecr.us-east-1.amazonaws.com

            docker pull 699480004844.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest

            docker stop innovatech-frontend || true
            docker rm innovatech-frontend || true

            docker run -d \
              --name innovatech-frontend \
              -p 80:80 \
              --restart always \
              699480004844.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest

            docker ps
          EOF